from Tkinter import *
root=Tk()
Frame=Frame(root,width=500,height=400)
Frame.pack()
Sensor1Label=Label(Frame,text="Sensor 1").grid(row=0, column=0)
cuadro1=Entry(Frame).grid(row=0, column=1)
Sensor2Label=Label(Frame,text="Sensor 2").grid(row=1, column=0)
cuadro2=Entry(Frame).grid(row=1, column=1)
Sensor3Label=Label(Frame,text="Sensor 3").grid(row=2, column=0)
cuadro3=Entry(Frame).grid(row=2, column=1)
Sensor4Label=Label(Frame,text="Sensor 4").grid(row=3, column=0)
cuadro4=Entry(Frame).grid(row=3, column=1)
Sensor5Label=Label(Frame,text="Sensor 5").grid(row=4, column=0)
cuadro5=Entry(Frame).grid(row=4, column=1)
Sensor6Label=Label(Frame,text="Sensor 6").grid(row=5, column=0)
cuadro6=Entry(Frame).grid(row=5, column=1)
Sensor7Label=Label(Frame,text="Sensor 7").grid(row=6, column=0)
cuadro7=Entry(Frame).grid(row=6, column=1)
root.title("Interfaz Nodo 611")
root.mainloop()